import { jsx as _jsx } from "react/jsx-runtime";
import { forwardRef } from 'react';
import { cn } from '@/lib/utils';
export const Card = forwardRef(({ className, ...props }, ref) => (_jsx("div", { ref: ref, className: cn('rounded-lg bg-white shadow-card', className), ...props })));
Card.displayName = 'Card';
export const CardHeader = forwardRef(({ className, ...props }, ref) => (_jsx("div", { ref: ref, className: cn('flex flex-col space-y-1.5 px-5 pt-5 pb-3', className), ...props })));
CardHeader.displayName = 'CardHeader';
export const CardTitle = forwardRef(({ className, ...props }, ref) => (_jsx("h3", { ref: ref, className: cn('font-semibold leading-tight tracking-heading text-ink-900 text-[17px]', className), ...props })));
CardTitle.displayName = 'CardTitle';
export const CardContent = forwardRef(({ className, ...props }, ref) => (_jsx("div", { ref: ref, className: cn('px-5 pb-5', className), ...props })));
CardContent.displayName = 'CardContent';
